
service: bookstore_ims

image: ghcr.io/sebc750/bookstoreimsnew

servers:
  web:
    hosts:
      - 68.183.114.68
    options:
      publish:
        - "3000:3000"

registry:
  server: ghcr.io  
  username: sebc750
  password:
    - GITHUB_PAT

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_ENV: production
    PORT: 3000
    SOLID_QUEUE_IN_PUMA: true

ssh:
  user: root

volumes:
  - "db:/rails/db"

asset_path: /rails/public/assets

builder:
  arch: amd64

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"

